import { EnergyProject, ProjectDocument } from "@/lib/types";

export const mockDocuments: ProjectDocument[] = [
  // Risk Money
  {
    id: "doc-1",
    projectId: "plts-te-8mwp",
    projectName: "PLTS Tanjung Enim 8 MWp",
    category: "Risk Money",
    title: "Risk Assessment Report - PLTS TE 8MWp",
    description: "Comprehensive risk assessment and financial risk analysis for the solar PV project",
    fileType: "PDF",
    fileSize: "2.4 MB",
    updatedAt: "2024-02-15",
  },
  {
    id: "doc-2",
    projectId: "pltu-smelter-inalum",
    projectName: "PLTU Smelter Inalum",
    category: "Risk Money",
    title: "Risk Assessment Report - PLTU Inalum",
    description: "Risk-return analysis for the coal-fired power plant project",
    fileType: "PDF",
    fileSize: "3.1 MB",
    updatedAt: "2024-03-01",
  },
  // Pitch Deck
  {
    id: "doc-3",
    projectId: "plts-te-8mwp",
    projectName: "PLTS Tanjung Enim 8 MWp",
    category: "Pitch Deck",
    title: "Investor Pitch Deck - PLTS TE",
    description: "Investment presentation for potential investors and stakeholders",
    fileType: "PPTX",
    fileSize: "5.8 MB",
    updatedAt: "2024-02-20",
  },
  {
    id: "doc-4",
    projectId: "pltu-smelter-inalum",
    projectName: "PLTU Smelter Inalum",
    category: "Pitch Deck",
    title: "Investor Pitch Deck - PLTU Inalum",
    description: "Project presentation for banking consortium and investors",
    fileType: "PPTX",
    fileSize: "7.2 MB",
    updatedAt: "2024-03-10",
  },
  // Business Pitch Deck
  {
    id: "doc-5",
    projectId: "plts-te-8mwp",
    projectName: "PLTS Tanjung Enim 8 MWp",
    category: "Business Pitch Deck",
    title: "Business Case - PLTS TE 8MWp",
    description: "Detailed business case analysis and financial projections",
    fileType: "PDF",
    fileSize: "4.1 MB",
    updatedAt: "2024-01-25",
  },
  {
    id: "doc-6",
    projectId: "plts-ikn-50mwp",
    projectName: "PLTS IKN Nusantara 50 MWp",
    category: "Business Pitch Deck",
    title: "Business Case - PLTS IKN",
    description: "Preliminary business case for the IKN solar project",
    fileType: "PDF",
    fileSize: "3.5 MB",
    updatedAt: "2024-04-01",
  },
  // RMM
  {
    id: "doc-7",
    projectId: "plts-te-8mwp",
    projectName: "PLTS Tanjung Enim 8 MWp",
    category: "RMM",
    title: "Risk Mitigation & Monitoring - PLTS TE",
    description: "Risk mitigation matrix and ongoing monitoring framework",
    fileType: "XLSX",
    fileSize: "1.8 MB",
    updatedAt: "2024-02-28",
  },
  {
    id: "doc-8",
    projectId: "pltu-smelter-inalum",
    projectName: "PLTU Smelter Inalum",
    category: "RMM",
    title: "Risk Mitigation & Monitoring - PLTU Inalum",
    description: "Comprehensive risk matrix with monitoring plan and KRIs",
    fileType: "XLSX",
    fileSize: "2.2 MB",
    updatedAt: "2024-03-05",
  },
  // BOL
  {
    id: "doc-9",
    projectId: "plts-te-8mwp",
    projectName: "PLTS Tanjung Enim 8 MWp",
    category: "BOL",
    title: "Board of Letter - PLTS TE 8MWp",
    description: "Official board correspondence and approval documents",
    fileType: "PDF",
    fileSize: "1.2 MB",
    updatedAt: "2024-03-15",
  },
  // External Data
  {
    id: "doc-10",
    projectId: "plts-te-8mwp",
    projectName: "PLTS Tanjung Enim 8 MWp",
    category: "External Data",
    title: "Solar Irradiance Study - Tanjung Enim",
    description: "Independent solar resource assessment and yield prediction report",
    fileType: "PDF",
    fileSize: "6.3 MB",
    updatedAt: "2024-01-10",
  },
  {
    id: "doc-11",
    projectId: "pltu-smelter-inalum",
    projectName: "PLTU Smelter Inalum",
    category: "External Data",
    title: "Environmental Impact Study - Kuala Tanjung",
    description: "Third-party environmental impact assessment report",
    fileType: "PDF",
    fileSize: "8.7 MB",
    updatedAt: "2024-02-05",
  },
  {
    id: "doc-12",
    projectId: "plts-ikn-50mwp",
    projectName: "PLTS IKN Nusantara 50 MWp",
    category: "External Data",
    title: "IKN Energy Master Plan Extract",
    description: "Relevant sections from IKN energy master plan for renewable targets",
    fileType: "PDF",
    fileSize: "4.9 MB",
    updatedAt: "2024-04-15",
  },
];

export const mockProjects: EnergyProject[] = [
  {
    id: "plts-te-8mwp",
    overview: {
      projectName: "PLTS Tanjung Enim 8 MWp",
      description:
        "Pembangunan Pembangkit Listrik Tenaga Surya (PLTS) dengan kapasitas 8 MWp di area reklamasi tambang PT Bukit Asam, Tanjung Enim. Proyek ini memanfaatkan lahan pasca tambang untuk menghasilkan energi bersih dan mendukung transisi energi perusahaan menuju net-zero emission.",
      capacity: "8 MWp",
      location: "Tanjung Enim, Sumatera Selatan",
      projectImage: "",
      keyAdvantage:
        "Pemanfaatan lahan reklamasi pasca tambang yang luas, radiasi matahari tinggi sepanjang tahun, dekat dengan jaringan transmisi PLN, mendukung komitmen ESG perusahaan.",
      plnConnection: "Terhubung ke Gardu Induk 150kV Tanjung Enim",
      competitiveAdvantage:
        "Biaya lahan rendah karena menggunakan area reklamasi sendiri, pengalaman PTBA dalam pengelolaan lahan besar, dukungan regulasi pemerintah untuk energi terbarukan.",
      background:
        "Sejalan dengan visi PTBA untuk bertransformasi dari perusahaan batubara menjadi perusahaan energi, proyek PLTS ini merupakan langkah strategis dalam diversifikasi portofolio energi. Proyek ini juga mendukung target pemerintah untuk bauran energi terbarukan 23% pada tahun 2025.",
    },
    status: "On Progress",
    timeline: [
      {
        id: "t1",
        activity: "Feasibility Study",
        startDate: "2024-01-15",
        endDate: "2024-03-31",
        stageActivity: "Pre-Development",
        stage: "Study",
        estimatePeriod: "3 bulan",
      },
      {
        id: "t2",
        activity: "Perizinan & Legalitas",
        startDate: "2024-03-01",
        endDate: "2024-06-30",
        stageActivity: "Development",
        stage: "Licensing",
        estimatePeriod: "4 bulan",
      },
      {
        id: "t3",
        activity: "Engineering & Procurement",
        startDate: "2024-05-01",
        endDate: "2024-08-31",
        stageActivity: "Development",
        stage: "EPC",
        estimatePeriod: "4 bulan",
      },
      {
        id: "t4",
        activity: "Konstruksi & Instalasi",
        startDate: "2024-07-01",
        endDate: "2024-10-31",
        stageActivity: "Construction",
        stage: "Build",
        estimatePeriod: "4 bulan",
      },
      {
        id: "t5",
        activity: "Commissioning & COD",
        startDate: "2024-10-01",
        endDate: "2024-12-31",
        stageActivity: "Commissioning",
        stage: "Testing",
        estimatePeriod: "3 bulan",
      },
    ],
    financial: {
      financialNote:
        "Proyek PLTS 8 MWp ini memiliki prospek finansial yang menarik dengan dukungan skema BOOT (Build-Own-Operate-Transfer) selama 25 tahun. Pendapatan utama berasal dari penjualan listrik ke PLN melalui PPA.",
      npv: 45000000000,
      irr: 14.5,
      paybackPeriod: "7.2 tahun",
      waccCalculation: 10.5,
      capitalExpenditure: 120000000000,
      tariff: "Rp 1.200/kWh (sesuai Permen ESDM)",
      mainCriteriaIndication:
        "IRR di atas WACC, NPV positif, payback period di bawah 10 tahun. Proyek layak secara finansial.",
    },
    risks: [
      {
        id: "r1",
        riskScore: 12,
        type: "Teknis",
        riskArea: "Kualitas Panel Surya",
        controlStatus: "Mitigated",
        levelScore: 3,
        impactScore: 4,
        riskStatus: "Medium",
        riskTreatment: "Pemilihan vendor panel tier-1 dengan garansi 25 tahun",
      },
      {
        id: "r2",
        riskScore: 8,
        type: "Regulasi",
        riskArea: "Perubahan Tarif PLN",
        controlStatus: "Monitored",
        levelScore: 2,
        impactScore: 4,
        riskStatus: "Medium",
        riskTreatment: "Klausul eskalasi tarif dalam PPA",
      },
      {
        id: "r3",
        riskScore: 6,
        type: "Lingkungan",
        riskArea: "Cuaca Ekstrem",
        controlStatus: "Mitigated",
        levelScore: 2,
        impactScore: 3,
        riskStatus: "Low",
        riskTreatment: "Desain struktur tahan angin kencang dan banjir",
      },
    ],
    legal: {
      legalAspect1: "Perjanjian Jual Beli Listrik (PPA) dengan PLN untuk durasi 25 tahun",
      notariat: "Akta Pendirian SPV untuk proyek PLTS telah disahkan",
      material: "Kontrak pengadaan panel surya dan inverter dengan vendor internasional",
      lingkungan: "AMDAL telah disetujui oleh DLHK Provinsi Sumatera Selatan",
      keamanan: "Sistem keamanan 24/7 dengan CCTV dan petugas keamanan",
      perizinan: "IUPTLS (Izin Usaha Penyediaan Tenaga Listrik untuk Kepentingan Sendiri) dalam proses",
      labor: "Tenaga kerja lokal 60% dari total kebutuhan konstruksi",
      keselamatan: "Standar K3 sesuai PP No. 50 Tahun 2012",
      regulasi: "Mengacu pada Permen ESDM No. 26 Tahun 2021 tentang PLTS Atap",
      asuransi: "All-risk insurance selama masa konstruksi dan operasi",
    },
    actionPlan: [
      {
        id: "a1",
        kegiatan: "Penyelesaian AMDAL",
        issues: "Dokumen tambahan diperlukan dari DLHK",
        sample: "Revisi dokumen AMDAL",
        actionPlan: "Koordinasi intensif dengan DLHK dan konsultan lingkungan",
        targetWaktu: "Q1 2024",
      },
      {
        id: "a2",
        kegiatan: "Tender EPC",
        issues: "Evaluasi teknis vendor",
        sample: "Dokumen tender",
        actionPlan: "Proses tender terbuka dengan minimum 3 peserta",
        targetWaktu: "Q2 2024",
      },
      {
        id: "a3",
        kegiatan: "PPA Signing",
        issues: "Negosiasi tarif dengan PLN",
        sample: "Draft PPA",
        actionPlan: "Negosiasi final tarif dan terms dengan PLN",
        targetWaktu: "Q2 2024",
      },
    ],
    progressMonitoring: {
      progressReport:
        "Feasibility study telah selesai dengan hasil positif. Proses perizinan AMDAL sedang berjalan di DLHK Sumatera Selatan. Tim EPC sudah memulai preliminary design. Target COD tetap pada Q4 2024.",
      report:
        "Progress keseluruhan proyek mencapai 35%. Fase pre-development telah selesai. Saat ini memasuki fase development dengan fokus pada perizinan dan procurement. Tidak ada deviasi signifikan dari rencana awal.",
    },
    externalData: {
      technicalStudy: {
        projectCertification: "Sertifikasi teknis dari Lembaga Sertifikasi Profesi bidang Energi Terbarukan",
        technicalReport: "Laporan teknis solar irradiance dan yield assessment oleh konsultan independen",
        demandAnalysis: "Analisis kebutuhan listrik regional Sumatera Selatan menunjukkan defisit 200 MW",
        terminalSpin: "Grid connection study menunjukkan kapasitas tersedia di GI 150kV Tanjung Enim",
      },
      submission: {
        ptbaDescription: "PT Bukit Asam Tbk merupakan perusahaan tambang batubara terbesar di Indonesia",
        ptbaGoals: "Transformasi menuju perusahaan energi terintegrasi dengan portofolio energi bersih",
        ebdInitiatives: "Pengembangan 500 MWp PLTS di lahan reklamasi PTBA secara bertahap",
        strategic: "Proyek PLTS 8 MWp sebagai pilot project untuk pengembangan skala besar",
      },
    },
    documents: mockDocuments.filter((d) => d.projectId === "plts-te-8mwp"),
  },
  {
    id: "pltu-smelter-inalum",
    overview: {
      projectName: "PLTU Smelter Inalum 2x150 MW",
      description:
        "Pembangunan Pembangkit Listrik Tenaga Uap (PLTU) untuk memasok kebutuhan listrik smelter aluminium PT Inalum di Kuala Tanjung, Sumatera Utara. Proyek ini menggunakan teknologi Ultra-Supercritical untuk efisiensi tinggi dan emisi rendah.",
      capacity: "2x150 MW (300 MW Total)",
      location: "Kuala Tanjung, Sumatera Utara",
      projectImage: "",
      keyAdvantage:
        "Pasokan batubara dari PTBA sendiri, lokasi strategis dekat pelabuhan, kebutuhan listrik captive dari smelter Inalum, teknologi ultra-supercritical efisiensi tinggi.",
      plnConnection: "Captive power untuk smelter Inalum + excess power ke grid PLN",
      competitiveAdvantage:
        "Integrasi vertikal dengan supply batubara PTBA, off-taker pasti (Inalum), skala ekonomi yang besar, sinergi antar BUMN melalui holding MIND ID.",
      background:
        "Proyek ini merupakan bagian dari grand strategy MIND ID untuk memperkuat rantai nilai industri aluminium nasional. PTBA sebagai pemasok energi utama mendukung operasi smelter Inalum yang membutuhkan pasokan listrik stabil dan kompetitif.",
    },
    status: "On Progress",
    timeline: [
      {
        id: "t1",
        activity: "Pre-FS & Site Assessment",
        startDate: "2024-01-01",
        endDate: "2024-02-29",
        stageActivity: "Pre-Development",
        stage: "Study",
        estimatePeriod: "2 bulan",
      },
      {
        id: "t2",
        activity: "Feasibility Study",
        startDate: "2024-02-01",
        endDate: "2024-05-31",
        stageActivity: "Pre-Development",
        stage: "Study",
        estimatePeriod: "4 bulan",
      },
      {
        id: "t3",
        activity: "Perizinan & AMDAL",
        startDate: "2024-04-01",
        endDate: "2024-08-31",
        stageActivity: "Development",
        stage: "Licensing",
        estimatePeriod: "5 bulan",
      },
      {
        id: "t4",
        activity: "EPC Procurement",
        startDate: "2024-07-01",
        endDate: "2024-10-31",
        stageActivity: "Development",
        stage: "EPC",
        estimatePeriod: "4 bulan",
      },
      {
        id: "t5",
        activity: "Construction Phase 1",
        startDate: "2024-09-01",
        endDate: "2024-12-31",
        stageActivity: "Construction",
        stage: "Build",
        estimatePeriod: "4 bulan",
      },
    ],
    financial: {
      financialNote:
        "Proyek PLTU 2x150 MW merupakan investasi skala besar dengan pendapatan terjamin dari captive power agreement dengan Inalum. Model bisnis BOOT 30 tahun memberikan return yang atraktif bagi investor.",
      npv: 890000000000,
      irr: 16.2,
      paybackPeriod: "8.5 tahun",
      waccCalculation: 11.0,
      capitalExpenditure: 4500000000000,
      tariff: "Rp 850/kWh (captive rate) + Rp 1.100/kWh (excess to PLN)",
      mainCriteriaIndication:
        "IRR 16.2% melampaui hurdle rate 12%. NPV sangat positif. Proyek sangat layak secara finansial dengan off-taker pasti.",
    },
    risks: [
      {
        id: "r1",
        riskScore: 16,
        type: "Finansial",
        riskArea: "Overrun Biaya Konstruksi",
        controlStatus: "Monitored",
        levelScore: 4,
        impactScore: 4,
        riskStatus: "High",
        riskTreatment: "Fixed-price EPC contract dengan performance guarantee",
      },
      {
        id: "r2",
        riskScore: 12,
        type: "Regulasi",
        riskArea: "Kebijakan Transisi Energi",
        controlStatus: "Monitored",
        levelScore: 3,
        impactScore: 4,
        riskStatus: "Medium",
        riskTreatment: "Penggunaan teknologi USC untuk memenuhi standar emisi ketat",
      },
      {
        id: "r3",
        riskScore: 9,
        type: "Teknis",
        riskArea: "Ketersediaan Pasokan Batubara",
        controlStatus: "Mitigated",
        levelScore: 3,
        impactScore: 3,
        riskStatus: "Medium",
        riskTreatment: "Coal supply agreement jangka panjang dengan PTBA",
      },
      {
        id: "r4",
        riskScore: 6,
        type: "Lingkungan",
        riskArea: "Emisi & Limbah",
        controlStatus: "Mitigated",
        levelScore: 2,
        impactScore: 3,
        riskStatus: "Low",
        riskTreatment: "Teknologi USC + FGD + ESP untuk kontrol emisi",
      },
    ],
    legal: {
      legalAspect1: "Captive Power Agreement dengan PT Inalum untuk pasokan listrik 25 tahun",
      notariat: "Perjanjian kerjasama PTBA-Inalum telah ditandatangani",
      material: "MoU pengadaan boiler dan turbin dengan vendor EPC internasional",
      lingkungan: "Dokumen AMDAL dalam proses penyusunan dengan konsultan lingkungan",
      keamanan: "Rencana pengamanan area PLTU sesuai standar ESDM",
      perizinan: "IUPTL dalam proses pengajuan ke Kementerian ESDM",
      labor: "Rencana penggunaan tenaga kerja lokal 50% dan nasional 40%",
      keselamatan: "Standar K3 konstruksi pembangkit sesuai regulasi Kemnaker",
      regulasi: "Mengacu pada PP No. 79/2014 tentang Kebijakan Energi Nasional",
      asuransi: "CAR (Contractor All Risk) + Third Party Liability Insurance",
    },
    actionPlan: [
      {
        id: "a1",
        kegiatan: "Finalisasi FS",
        issues: "Data teknis site masih dikumpulkan",
        sample: "Laporan FS",
        actionPlan: "Percepatan pengumpulan data geoteknik dan hidro",
        targetWaktu: "Q2 2024",
      },
      {
        id: "a2",
        kegiatan: "Proses AMDAL",
        issues: "Persetujuan dari masyarakat sekitar",
        sample: "Dokumen AMDAL",
        actionPlan: "Sosialisasi dan public hearing dengan masyarakat lokal",
        targetWaktu: "Q3 2024",
      },
      {
        id: "a3",
        kegiatan: "Seleksi EPC Contractor",
        issues: "Evaluasi teknis dan komersial",
        sample: "RFP EPC",
        actionPlan: "International competitive bidding untuk EPC contractor",
        targetWaktu: "Q3 2024",
      },
      {
        id: "a4",
        kegiatan: "Financial Close",
        issues: "Structuring pembiayaan",
        sample: "Term sheet",
        actionPlan: "Negosiasi dengan konsorsium perbankan untuk project finance",
        targetWaktu: "Q4 2024",
      },
    ],
    progressMonitoring: {
      progressReport:
        "Pre-feasibility study telah selesai. Feasibility study sedang berjalan oleh konsultan independen. Proses sosialisasi dengan masyarakat sekitar lokasi proyek telah dimulai. MoU dengan Inalum telah ditandatangani.",
      report:
        "Progress keseluruhan 20%. Fase pre-development berjalan sesuai jadwal. Identifikasi risiko utama telah dilakukan. Tim proyek telah terbentuk dengan penunjukan Project Director dan Project Manager.",
    },
    externalData: {
      technicalStudy: {
        projectCertification: "Pre-certification dari Kementerian ESDM untuk pembangunan PLTU baru",
        technicalReport: "Studi kelayakan teknis oleh konsultan EPC internasional",
        demandAnalysis: "Kebutuhan listrik smelter Inalum: 250 MW untuk operasi penuh",
        terminalSpin: "Studi koneksi grid dan analisis stabilitas sistem kelistrikan Sumut",
      },
      submission: {
        ptbaDescription: "PT Bukit Asam Tbk - perusahaan energi terintegrasi anggota holding MIND ID",
        ptbaGoals: "Menjadi penyedia solusi energi terdepan untuk industri strategis nasional",
        ebdInitiatives: "Pengembangan captive power untuk industri hilirisasi mineral dan logam",
        strategic: "Sinergi BUMN melalui MIND ID untuk memperkuat rantai nilai aluminium nasional",
      },
    },
    documents: mockDocuments.filter((d) => d.projectId === "pltu-smelter-inalum"),
  },
  {
    id: "plts-ikn-50mwp",
    overview: {
      projectName: "PLTS IKN Nusantara 50 MWp",
      description:
        "Rencana pembangunan Pembangkit Listrik Tenaga Surya skala besar di kawasan Ibu Kota Nusantara (IKN) untuk mendukung visi kota hijau dan smart city. Proyek ini merupakan bagian dari komitmen pemerintah menjadikan IKN sebagai kota dengan 100% energi bersih.",
      capacity: "50 MWp",
      location: "IKN Nusantara, Kalimantan Timur",
      projectImage: "",
      keyAdvantage:
        "Dukungan penuh pemerintah untuk IKN green city, lahan tersedia luas, potensi solar resource tinggi, prestige proyek nasional.",
      plnConnection: "Terhubung ke smart grid IKN Nusantara",
      competitiveAdvantage:
        "First mover advantage di IKN, hubungan baik dengan Otorita IKN, pengalaman PTBA dalam proyek PLTS, akses ke pembiayaan hijau (green financing).",
      background:
        "Ibu Kota Nusantara didesain sebagai smart forest city dengan target 100% energi terbarukan. PTBA melihat peluang besar untuk berkontribusi dalam penyediaan energi bersih di IKN sebagai bagian dari transformasi bisnis perusahaan.",
    },
    status: "Planning",
    timeline: [
      {
        id: "t1",
        activity: "Studi Awal & Site Selection",
        startDate: "2025-01-01",
        endDate: "2025-03-31",
        stageActivity: "Pre-Development",
        stage: "Study",
        estimatePeriod: "3 bulan",
      },
      {
        id: "t2",
        activity: "MoU dengan Otorita IKN",
        startDate: "2025-03-01",
        endDate: "2025-04-30",
        stageActivity: "Pre-Development",
        stage: "Agreement",
        estimatePeriod: "2 bulan",
      },
    ],
    financial: {
      financialNote:
        "Proyeksi finansial masih bersifat indikatif menunggu hasil feasibility study. Potensi akses green bond dan climate finance untuk pembiayaan proyek.",
      npv: 180000000000,
      irr: 13.8,
      paybackPeriod: "8 tahun (estimasi)",
      waccCalculation: 9.5,
      capitalExpenditure: 750000000000,
      tariff: "TBD - mengacu pada regulasi tarif EBT terbaru",
      mainCriteriaIndication:
        "Estimasi awal menunjukkan kelayakan finansial yang baik. Perlu FS detail untuk konfirmasi.",
    },
    risks: [
      {
        id: "r1",
        riskScore: 12,
        type: "Politik",
        riskArea: "Keberlanjutan Proyek IKN",
        controlStatus: "Monitored",
        levelScore: 3,
        impactScore: 4,
        riskStatus: "Medium",
        riskTreatment: "Diversifikasi off-taker tidak hanya IKN",
      },
      {
        id: "r2",
        riskScore: 9,
        type: "Teknis",
        riskArea: "Infrastruktur Grid IKN",
        controlStatus: "Monitored",
        levelScore: 3,
        impactScore: 3,
        riskStatus: "Medium",
        riskTreatment: "Koordinasi dengan PLN untuk pengembangan grid IKN",
      },
    ],
    legal: {
      legalAspect1: "Dalam proses penjajakan MoU dengan Otorita IKN",
      notariat: "Belum dimulai",
      material: "Belum dimulai - menunggu hasil FS",
      lingkungan: "Kajian lingkungan awal (KLA) akan dilakukan bersamaan dengan FS",
      keamanan: "Akan mengikuti standar keamanan kawasan IKN",
      perizinan: "Koordinasi awal dengan Otorita IKN untuk perizinan khusus kawasan",
      labor: "Rencana prioritas tenaga kerja lokal Kalimantan Timur",
      keselamatan: "Akan mengacu pada standar K3 nasional",
      regulasi: "Mengacu pada PP IKN dan regulasi EBT terkait",
      asuransi: "Akan ditentukan pada fase development",
    },
    actionPlan: [
      {
        id: "a1",
        kegiatan: "Penjajakan Awal IKN",
        issues: "Akses ke Otorita IKN",
        sample: "Proposal kerjasama",
        actionPlan: "Approach melalui MIND ID dan Kementerian BUMN",
        targetWaktu: "Q1 2025",
      },
    ],
    progressMonitoring: {
      progressReport:
        "Tahap inisiasi proyek. Tim business development sedang menyusun proposal kerjasama untuk Otorita IKN. Studi desktop mengenai potensi solar resource di Kalimantan Timur telah selesai.",
      report:
        "Proyek masih dalam fase planning. Progress 5%. Fokus saat ini pada business case development dan stakeholder engagement.",
    },
    externalData: {
      technicalStudy: {
        projectCertification: "Belum dimulai",
        technicalReport: "Desktop study solar resource assessment Kalimantan Timur telah selesai",
        demandAnalysis: "Estimasi kebutuhan listrik IKN fase 1: 300 MW (target EBT 100%)",
        terminalSpin: "Studi awal integrasi dengan smart grid IKN",
      },
      submission: {
        ptbaDescription: "PT Bukit Asam Tbk berkomitmen mendukung pembangunan IKN Nusantara",
        ptbaGoals: "Menjadi penyedia energi bersih utama untuk IKN Nusantara",
        ebdInitiatives: "Pengembangan PLTS utility-scale untuk smart city IKN",
        strategic: "Positioning PTBA sebagai mitra strategis energi bersih IKN",
      },
    },
    documents: mockDocuments.filter((d) => d.projectId === "plts-ikn-50mwp"),
  },
];

export function getProjectById(id: string): EnergyProject | undefined {
  return mockProjects.find((p) => p.id === id);
}

export function getDocumentsByCategory(category: string): ProjectDocument[] {
  return mockDocuments.filter((d) => d.category === category);
}

export function createEmptyProject(): EnergyProject {
  return {
    id: "",
    overview: {
      projectName: "",
      description: "",
      capacity: "",
      location: "",
      projectImage: "",
      keyAdvantage: "",
      plnConnection: "",
      competitiveAdvantage: "",
      background: "",
    },
    status: "Planning",
    timeline: [],
    financial: {
      financialNote: "",
      npv: 0,
      irr: 0,
      paybackPeriod: "",
      waccCalculation: 0,
      capitalExpenditure: 0,
      tariff: "",
      mainCriteriaIndication: "",
    },
    risks: [],
    legal: {
      legalAspect1: "",
      notariat: "",
      material: "",
      lingkungan: "",
      keamanan: "",
      perizinan: "",
      labor: "",
      keselamatan: "",
      regulasi: "",
      asuransi: "",
    },
    actionPlan: [],
    progressMonitoring: {
      progressReport: "",
      report: "",
    },
    externalData: {
      technicalStudy: {
        projectCertification: "",
        technicalReport: "",
        demandAnalysis: "",
        terminalSpin: "",
      },
      submission: {
        ptbaDescription: "",
        ptbaGoals: "",
        ebdInitiatives: "",
        strategic: "",
      },
    },
    documents: [],
  };
}
